[package]
name = "proxychains"
version = "0.1.0"
authors = ["farokh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
futures = "0.3.4"
tokio = { version = "0.2.20", features = ["full"] }
mpsc2way = {path ="../atossa/mpsc2way"}
futures-util = "0.3"
url = "2.1"
tungstenite = "0.10"
tokio-tungstenite = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "2.33.1"

[lib]
name = "proxychains"
crate_type = ["dylib"]
